### ISSUE TITLE
Used your code

### ISSUE THREAD

**Issue by txemi** [khe35280/music_in_python#1]
Hi katieshiquhe, I wanted to inform you that I used your code on:

https://github.com/txemi/txpymusiclib

and it was very useful to me, thank you.

You also can find it as your project fork in:

https://github.com/txemi/music_in_python

I have mentioned you on README.

I also would like to release my code with GPL, would you agree?

Thank you

**Comment by katieshiqihe** [comment]
Hi @txemi,

Thanks for bring it up here and the attribution. I have added a MIT license to the repo: you are free to use, modify, and distribute the code as you see fit.

Best,
Katie
